// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/vitalijb/ralphex/pkg/executor"
)

// ExecutorMock is a mock implementation of processor.Executor.
//
//	func TestSomethingThatUsesExecutor(t *testing.T) {
//
//		// make and configure a mocked processor.Executor
//		mockedExecutor := &ExecutorMock{
//			RunFunc: func(ctx context.Context, prompt string) executor.Result {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedExecutor in code that requires processor.Executor
//		// and then make assertions.
//
//	}
type ExecutorMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, prompt string) executor.Result

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Prompt is the prompt argument value.
			Prompt string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *ExecutorMock) Run(ctx context.Context, prompt string) executor.Result {
	if mock.RunFunc == nil {
		panic("ExecutorMock.RunFunc: method is nil but Executor.Run was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Prompt string
	}{
		Ctx:    ctx,
		Prompt: prompt,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, prompt)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedExecutor.RunCalls())
func (mock *ExecutorMock) RunCalls() []struct {
	Ctx    context.Context
	Prompt string
} {
	var calls []struct {
		Ctx    context.Context
		Prompt string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
